# In file: config/amr_slam.yaml

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner::SmacPlanner2D"
      tolerance: 0.5
      allow_unknown: true

# ในไฟล์ config/amr_slam.yaml
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity: 0.0
    min_y_velocity: 0.0
    min_theta_velocity: 0.0

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

      # 1. ลิสต์ของชื่อ critics (เหมือนสารบัญ)
      critics:
        ["GoalAlign", "PathDist", "PathAlign", "GoalDist", "RotateToGoal"]
      # 2. บล็อกการตั้งค่าของแต่ละ critic ที่อยู่ในลิสต์ข้างบน
      GoalAlign:
        plugin: "dwb_critics::GoalAlign"
        scale: 32.0 # <--- เมื่อแยกบล็อกแล้ว สามารถกลับมาใช้ .0 ได้
      PathDist:
        plugin: "dwb_critics::PathDist"
        scale: 32.0
      PathAlign:
        plugin: "dwb_critics::PathAlign"
        scale: 32.0
      GoalDist:
        plugin: "dwb_critics::GoalDist"
        scale: 24.0
      RotateToGoal:
        plugin: "dwb_critics::RotateToGoal"
        scale: 32.0

global_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: "map"
    robot_base_frame: "base_footprint"
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      {
        plugin: "nav2_costmap_2d::StaticLayer",
        map_subscribe_transient_local: true,
      }
    obstacle_layer:
      {
        plugin: "nav2_costmap_2d::ObstacleLayer",
        observation_sources: "scan",
        scan: { topic: "/scan_corrected", data_type: "LaserScan" },
      }
    inflation_layer:
      { plugin: "nav2_costmap_2d::InflationLayer", inflation_radius: 0.2 }

local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: "odom"
    robot_base_frame: "base_footprint"
    width: 3
    height: 3
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      {
        plugin: "nav2_costmap_2d::ObstacleLayer",
        footprint_clearing_enabled: true,
        observation_sources: "scan",
        scan: { topic: "/scan_corrected", data_type: "LaserScan" },
      }
    inflation_layer:
      { plugin: "nav2_costmap_2d::InflationLayer", inflation_radius: 0.15 }

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml"

# This name MUST match the 'name' field in the explore_node definition
explore:
  ros__parameters:
    use_sim_time: true
    planner_frequency: 0.5
    progress_timeout: 30.0
    potential_scale: 3.0
    orientation_scale: 0.0
    gain_scale: 1.0
    transform_tolerance: 0.5
    min_frontier_size: 0.5

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - "planner_server"
      - "controller_server"
      - "behavior_server"
      - "bt_navigator"
      - "velocity_smoother"
      - "collision_monitor"
