# In config/ekf.yaml

ekf_filter_node:
  ros__parameters:
    # Freq, sensor timeout, etc.
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true

    # --- ADD THIS LINE ---
    use_sim_time: true
    # ---------------------

    # Frames
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # Sensor configuration (odom0, imu0)
    odom0: /odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false

    imu0: /imu
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, false,
                  false, false, false, false]
    imu0_differential: false